- name: Apply GPO and Privilege Hardening Policies
  hosts: windows
  become: yes
  tasks:

    # ------------------------------
    # GPO Hardening Policies
    # ------------------------------

    - name: Enforce Account Lockout Policy (Windows)
      ansible.windows.win_command: >
        secedit /configure /db c:\windows\security\local.sdb
        /cfg c:\windows\security\templates\hardening.inf

    - name: Create Security Template for Account Lockout
      ansible.windows.win_template:
        src: templates/hardening.inf.j2
        dest: c:\windows\security\templates\hardening.inf

    - name: Ensure Windows Firewall is Enabled
      ansible.windows.win_shell: netsh advfirewall set allprofiles state on

    - name: Disable Guest Account
      ansible.windows.win_user:
        name: Guest
        state: absent

    # ------------------------------
    # Privilege Hardening Policies
    # ------------------------------

    - name: Deny Local Logon for Non-Admins
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LocalAccountTokenFilterPolicy
        data: 0
        type: dword

    - name: Restrict RDP Access to Administrators Only
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
        name: SecurityLayer
        data: 2
        type: dword

    - name: Enforce Least Privilege by Disabling Built-in Administrator
      ansible.windows.win_user:
        name: Administrator
        state: disabled

    - name: Remove All Users from Remote Desktop Users Group
      ansible.windows.win_shell: net localgroup "Remote Desktop Users" /delete

    # ------------------------------
    # Debug and Confirmation
    # ------------------------------

    - name: Debug GPO and Privilege Hardening
      ansible.builtin.debug:
        msg: "GPO and privilege hardening policies have been applied to {{ inventory_hostname }}"
