- name: Synchronize Time and Create Admin Users
  hosts: all
  become: yes
  tasks:

    # ------------------------------
    # Time Synchronization Tasks
    # ------------------------------

    - name: Ensure NTP is Installed on Rocky Linux
      ansible.builtin.yum:
        name: chrony
        state: present
      when: "'rocky' in group_names"

    - name: Enable and Start NTP Service on Rocky Linux
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      when: "'rocky' in group_names"

    - name: Configure Windows Time Service
      ansible.windows.win_shell: |
        w32tm /config /manualpeerlist:"time.windows.com,0x1" /syncfromflags:manual /reliable:YES /update
        w32tm /resync
      when: "'windows' in group_names"

    - name: Ensure Windows Time Service is Running
      ansible.windows.win_service:
        name: W32Time
        start_mode: auto
        state: started
      when: "'windows' in group_names"

    # ------------------------------
    # Admin User Creation
    # ------------------------------

    - name: Create Admin User on Windows
      ansible.windows.win_user:
        name: ansibleadmin
        password: "SecurePass123!"
        groups:
          - Administrators
        state: present
      when: "'windows' in group_names"

    - name: Create Admin User on Rocky Linux
      ansible.builtin.user:
        name: ansibleadmin
        password: "{{ 'SecurePass123!' | password_hash('sha512') }}"
        groups: wheel
        state: present
      when: "'rocky' in group_names"

    - name: Ensure Admin User has sudo Access on Linux
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/ansibleadmin"
        content: "ansibleadmin ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      when: "'rocky' in group_names"

    # ------------------------------
    # Debug and Confirmation
    # ------------------------------

    - name: Debug Sync Time and Admin User Setup
      ansible.builtin.debug:
        msg: "Time synchronization and admin user creation completed on {{ inventory_hostname }}"
